services:
  postgres:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=vbos
    image: postgis/postgis:17-3.5
    platform: linux/x86_64
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 5
  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
    build: ./
    command: >
      bash -c "python3 wait_for_postgres.py &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  documentation:
    restart: always
    build: ./
    command: "python3 -m mkdocs serve"
    volumes:
      - ./:/code
    ports:
      - "8001:8001"
