services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
      - /home/devseed/vbos-backend/static:/www/html/static
    restart: unless-stopped
    # labels:
    #   caddy.debug:

networks:
  caddy:
    external: true

volumes:
  caddy_data: {}
